# =========================
# SonarCloud Configuration
# =========================

sonar.projectKey=HeckoDev_H.A.N.A.
sonar.organization=heckodev

sonar.projectName=H.A.N.A.
sonar.projectVersion=1.0.0

sonar.newCode.referenceBranch=main

sonar.sources=app,server,nuxt.config.ts,tailwind.config.ts
sonar.tests=e2e

sonar.inclusions=app/**,server/**,nuxt.config.ts,tailwind.config.ts,e2e/**
sonar.exclusions=**/node_modules/**,**/.nuxt/**,**/.output/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/*.config.ts

sonar.test.inclusions=e2e/**,**/*.spec.ts,**/*.test.ts,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/__tests__/**,e2e/**,**/*.spec.ts,**/*.test.ts,**/*.config.ts,**/*.d.ts

sonar.sourceEncoding=UTF-8

sonar.typescript.tsconfigPath=tsconfig.json
