# =========================
# SonarCloud Configuration
# =========================

sonar.projectKey=HeckoDev_H.A.N.A.
sonar.organization=heckodev

sonar.projectName=H.A.N.A.
sonar.projectVersion=1.0.0

sonar.newCode.referenceBranch=main

sonar.sources=app,server,nuxt.config.ts,tailwind.config.ts
sonar.tests=tests

sonar.inclusions=app/**,server/**,nuxt.config.ts,tailwind.config.ts
sonar.exclusions=**/node_modules/**,**/.nuxt/**,**/.output/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/*.config.ts

sonar.test.inclusions=tests/**,**/*.spec.ts,**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=tests/**,**/*.spec.ts,**/*.test.ts,**/*.config.ts,**/*.d.ts

sonar.sourceEncoding=UTF-8

sonar.typescript.tsconfigPath=tsconfig.json
